use_frameworks!

target 'Zoomy_Example' do
  pod 'Zoomy', :path => '../'

  pod "Texture", "~> 3.0"
  
  target 'Zoomy_Tests' do
    inherit! :search_paths

    pod 'InjectableLoggers', '~> 2.0'
  end
end
